version: "3.8"

services:
  api:
    build: ./src
    ports:
      - "9000:9000"
    env_file:
      - ./src/.env

  ingestor:
    build: ./ingestor
    env_file:
     - ./ingestor/.env
    depends_on:
      - api
      - db
  
  web:
    build: ./web
    ports:
      - "8000:8000"
    env_file:
      - ./web/.env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: leaksdb
    ports:
      - "5432:5432"
   
